In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import os 
plt.rcParams['font.sans-serif'] = ['Noto Sans CJK SC']
plt.rcParams['axes.unicode_minus'] = False
import os 

from sklearn.metrics import normalized_mutual_info_score as NMI
from tqdm import tqdm
from esl import one_hot_encode_sequences, ESLClassifier, ESLPSCClassifier, leave_one_out_eval

## 展示ESL ESL_PSC的结果

选取top50特征

### ZWS demo

In [2]:
def pipe(species_id):
    # species_id = 'Sorex_araneus'
    dir_path = f'../phd_thesis/103_leave/{species_id}'
    feature_df = pd.read_csv(os.path.join(dir_path, 'df_feature.csv'), index_col = 0)
    meta_df = pd.read_csv(os.path.join(dir_path, 'df_meta.csv'),index_col = 0)
    summary_df = pd.read_csv(os.path.join(dir_path, 'df_summary.csv'),index_col = 0)
    assert (meta_df.index == feature_df.index).all()
    assert (summary_df.index == feature_df.columns).all()

    all_species = meta_df.index.to_list()
    train_species = meta_df.index.to_list()
    train_species.remove(species_id)

    train_label   = meta_df.loc[train_species, 'label'].values

    # 全量特征（含 species_id），用于最终全量预测
    def get_top_n(group, n=100):
        return group.nlargest(n, 'NMI')

    gene_list = []
    for ele in summary_df.index: 
        gene = ele.split('_')[0]
        gene_list.append(gene)
    summary_df.loc[:,'gene'] = gene_list
    summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

    all_feature = pd.read_parquet('/home/rsun@ZHANGroup.local/hqy_new/data_717/feature_df/data_raw.parquet')
    #train_feature = all_feature.loc[summary_top100.index,train_species].T 
    
    '''ESL 预测'''
    train_id = []
    for ele in all_species:
        if ele == species_id:
            train_id.append(False)
        else:
            train_id.append(True)
    train_id = np.array(train_id)
    res = []
    # one-hot 编码
    X, feature_names, group_ids, position_names, gene_names = one_hot_encode_sequences(all_feature.loc[summary_top100.index,all_species].T)
    X_train = X[train_id,:]
    X_test = X[~train_id,:]
    print(X_train.shape, X_test.shape)
    y = train_label 

    # 训练
    clf = ESLClassifier(lambda1=0.03, lambda2=0.01,tol = 1e-4, max_iter = 100)
    clf.fit(X_train, y, group_ids, feature_names=feature_names,
            position_names=position_names, gene_names=gene_names)

    # 预测
    y_pred = clf.predict(X_test)           # 0/1 标签
    proba = clf.predict_proba(X_test)      # shape (n, 2), 第1列为正类概率
    sps = clf.decision_function(X_test)    # Sequence Prediction Score
    print(f"eval {meta_df.loc[species_id,'label'],meta_df.loc[species_id,'species_chinese']}")
    print(f'ESL prediction label {y_pred}, eco proba {proba}')
    res = [species_id,meta_df.loc[species_id,'label'],meta_df.loc[species_id,'species_chinese'],y_pred, proba]
    
    '''ESL-PSC'''
    # 留出测试物种
    test_species = species_id
    seq_df = all_feature.loc[summary_top100.index,all_species].T
    train_sp = [s for s in seq_df.index if s != test_species]

    # 训练
    clf = ESLPSCClassifier(
        lambda1_list=[0.03],   # lambda1 搜索范围
        lambda2_list=[0.01],   # lambda2 搜索范围
        top_pct=0.3,                  # 保留 top 30% 的模型
        n_alternates=2,               # 每个 order 最多取2种配对
        order_col="order_chinese_new",
        label_col="label",
    )
    clf.fit(seq_df.loc[train_sp], meta_df.loc[train_sp],max_iter = 100,tol = 1e-4)

    # 单物种预测
    y_pred, proba, sps = clf.predict_species(seq_df, test_species)
    res.append(y_pred)
    res.append(proba)
    print(f'ESL-PSC prediction label {y_pred}, eco proba {proba}')
    print('==================================================================')
    return res

In [4]:
# pipe( species_id = 'Sorex_araneus')

In [7]:
import os
import multiprocessing

# if __name__ == '__main__':
data_dir = '../phd_thesis/103_leave/'
species_list = os.listdir(data_dir)

print(f"Found {len(species_list)} species. Starting parallel processing...")

all_results = [] # 用于存储所有物种的结果

# 使用进程池
with multiprocessing.Pool(processes=52) as pool:
    results_from_pool = pool.map(pipe, species_list)
    
# 聚合结果
for species, res in zip(species_list, results_from_pool):
    # res 是 pipe 返回的列表，例如 [(y_pred, proba)]
    # 你可以选择将其展平，或者保留结构
    all_results.extend(res) 
    
    # 如果需要记录哪个结果属于哪个物种，建议这样存：
    # for item in res:
    #     all_results.append({'species': species, 'pred': item[0], 'proba': item[1]})

print(f"Processing complete. Total records collected: {len(all_results)}")
    
    # 后续可以将 all_results 转换为 DataFrame 或其他格式进行分析
    # import pandas as pd
    # df_results = pd.DataFrame(all_results, columns=['y_pred', 'proba'])

Found 104 species. Starting parallel processing...

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

(103, 51123) (1, 51123)
(103, 51139) (1, 51139)
(103, 51341) (1, 51341)
(103, 49123) (1, 49123)
(103, 51238) (1, 51238)
(103, 51327) (1, 51327)
(103, 51214) (1, 51214)
(103, 51302) (103, 51282)(1, 51302)
(1, 51282)
(103, 51157) (1, 51157)
(103, 51157) (1, 51157)(103, 49355)
 (1, 49355)
(103, 51194) (1, 51194)
(103, 51301) (1, 51301)
(103, 50970) (1, 50970)(103, 51191)
(1, 51191)
(103, 51305) (1, 51305)
(103, 51324) (103, 51287)(1, 51324)
(1, 51287)
(103, 51154) (1, 51154)
(103, 49072) (1, 49072)
(103, 51225) (1, 51225)
(103, 51193) (1, 51193)(103, 51131)
 (103, 49194)(1, 51131)
(1, 49194)
(103, 51128) (1, 51128)
(103, 51364) (1, 51364)
(103, 51322) (1, 51322)
(103, 51067) (1, 51067)
(103, 51328) (1, 51328)
(103, 51216) (1, 51216)
(103, 51175) (1, 51175)
(103, 49504) (1, 49504)
(103, 51170)(103, 51238) (1, 51170)(103, 51266) (1, 51238)

 (1, 51266)
(103, 51264) (1, 51264)
(103, 49315) (1, 49315)
(103, 51253) (1, 51253)
(103, 51285) (1, 51285)
(103, 51195) (1, 51195)
(103, 49001) (1, 49001)
(103, 51210) (1, 51210)
(103, 51202) (1, 51202)
(103, 47511) (1, 47511)
(103, 51109) (1, 51109)
(103, 51173) (1, 51173)
(103, 51150) (1, 51150)
(103, 51180) (1, 51180)
(103, 51159) (1, 51159)
(103, 51228) (1, 51228)
(103, 51153) (1, 51153)
eval (0.0, '美洲野牛')
ESL prediction label [0], eco proba [[0.68366251 0.31633749]]
eval (0.0, '驴')
ESL prediction label [0], eco proba [[0.70543439 0.29456561]]
eval (1.0, '牙买加果蝠')
ESL prediction label [1], eco proba [[0.32102627 0.67897373]]
eval (1.0, '加湾鼠海豚')
ESL prediction label [1], eco proba [[0.32962265 0.67037735]]
eval (0.0, '山羊')
ESL prediction label [0], eco proba [[0.73514971 0.26485029]]
eval (1.0, '大叶口蝠')
ESL prediction label [1], eco proba [[0.31223595 0.68776405]]
eval (0.0, '美洲鼠兔')
ESL prediction label [0], eco proba [[0.68269374 0.31730626]]
eval (0.0, '海獭')
ESL prediction label [0], eco proba [[0.71246315 0.28753685]]
eval (0.0, '尼罗草鼠')
ESL prediction label [0], eco proba [[0.7192111 0.2807889]]
eval (1.0, '淡叶口蝠')
ESL prediction label [1], eco proba [[0.31198751 0.68801249]]
eval (0.0, '普通狨')
ESL prediction label [0], eco proba [[0.74389612 0.25610388]]
eval (0.0, '蓝鲸')
ESL prediction label [0], eco proba [[0.5030158 0.4969842]]
eval (0.0, '双峰驼')
ESL prediction label [0], eco proba [[0.6815085 0.3184915]]
eval (0.0, '阿尔卑斯旱獭')
ESL prediction label [0], eco proba [[0.71982667 0.28017333]]
eval (0.0, '加利利盲鼹鼠')
ESL prediction label [0], eco proba [[0.69197865 0.30802135]]
eval (0.0, '印度狐蝠')
ESL prediction label [1], eco proba [[0.37783395 0.62216605]]
eval (0.0, '黑猩猩')
ESL prediction label [0], eco proba [[0.74116145 0.25883855]]
eval (0.0, '滇金丝猴')
ESL prediction label [0], eco proba [[0.72817769 0.27182231]]
eval (0.0, '巴拿马白面卷尾猴')
ESL prediction label [0], eco proba [[0.73936589 0.26063411]]
eval (1.0, '白鱀豚')
ESL prediction label [1], eco proba [[0.37970723 0.62029277]]
eval (1.0, '大蹄蝠')
ESL prediction label [1], eco proba [[0.37484017 0.62515983]]
eval (0.0, '十三纹地松鼠')
ESL prediction label [0], eco proba [[0.6908182 0.3091818]]
eval (1.0, '纳塔尔长翼蝠')
ESL prediction label [1], eco proba [[0.32276455 0.67723545]]
eval (0.0, '乔氏猫')eval (0.0, '土拨鼠')


ESL prediction label [0], eco proba [[0.71913504 0.28086496]]ESL prediction label [0], eco proba [[0.72228191 0.27771809]]
eval (1.0, '吸血蝠')
ESL prediction label [1], eco proba [[0.34278398 0.65721602]]
eval (0.0, '亚洲象')
ESL prediction label [0], eco proba [[0.68296703 0.31703297]]
eval (1.0, '宽吻海豚')
ESL prediction label [1], eco proba [[0.31242478 0.68757522]]
eval (0.0, '平原斑马')
ESL prediction label [0], eco proba [[0.69571365 0.30428635]]
eval (0.0, '高原鼠兔')eval (0.0, '乌干达红疣猴')
ESL prediction label [0], eco proba [[0.74798335 0.25201665]]

ESL prediction label [0], eco proba [[0.69612337 0.30387663]]
eval (0.0, '中华树鼩')
ESL prediction label [0], eco proba [[0.70552756 0.29447244]]
eval (0.0, '东北虎')
ESL prediction label [0], eco proba [[0.50282758 0.49717242]]
eval (1.0, '虎鲸')
ESL prediction label [1], eco proba [[0.31663361 0.68336639]]
eval (0.0, '黑狐蝠')
ESL prediction label [1], eco proba [[0.4081373 0.5918627]]
eval (0.0, '科氏冕狐猴')
ESL prediction label [0], eco proba [[0.70682217 0.29317783]]
eval (1.0, '长肢领航鲸')
ESL prediction label [1], eco proba [[0.31630156 0.68369844]]
eval (0.0, '绵羊')
ESL prediction label [0], eco proba [[0.72176454 0.27823546]]
eval (1.0, '大菊头蝠')
ESL prediction label [1], eco proba [[0.3491109 0.6508891]]
eval (1.0, '白鲸')
ESL prediction label [1], eco proba [[0.32144751 0.67855249]]
eval (0.0, '美洲黑熊')
ESL prediction label [0], eco proba [[0.71334894 0.28665106]]
eval (0.0, '野牦牛')
ESL prediction label [0], eco proba [[0.72050492 0.27949508]]
eval (1.0, '独角鲸')eval (0.0, '家牛')
ESL prediction label [1], eco proba [[0.3338213 0.6661787]]

ESL prediction label [0], eco proba [[0.73254602 0.26745398]]
eval (0.0, '北极熊')
ESL prediction label [0], eco proba [[0.69064946 0.30935054]]
eval (0.0, '羊驼')
ESL prediction label [0], eco proba [[0.6989243 0.3010757]]
eval (0.0, '普氏野马')
ESL prediction label [0], eco proba [[0.67767668 0.32232332]]
eval (0.0, '黄腹旱獭')
ESL prediction label [0], eco proba [[0.73900973 0.26099027]]
eval (0.0, '北极地松鼠')
ESL prediction label [0], eco proba [[0.73161992 0.26838008]]
eval (0.0, '白犀牛')
ESL prediction label [0], eco proba [[0.6992423 0.3007577]]
eval (0.0, '星鼻鼹')
ESL prediction label [0], eco proba [[0.60783243 0.39216757]]
eval (0.0, '单峰驼')
ESL prediction label [0], eco proba [[0.69305964 0.30694036]]
ESL-PSC prediction label 0, eco proba 0.31516330009771026
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 52723) (1, 52723)
eval (1.0, '猪尾鼠')
ESL prediction label [0], eco proba [[0.60663396 0.39336604]]
ESL-PSC prediction label 1, eco proba 0.6749240764592347
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51129) (1, 51129)
ESL-PSC prediction label 1, eco proba 0.6918983630782557
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 1, eco proba 0.5777888570918518
==================================================================
(103, 51278) (1, 51278)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.31214723423470336
==================================================================
ESL-PSC prediction label 1, eco proba 0.752904276209561
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51174) (1, 51174)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.254234718641537
ESL-PSC prediction label 0, eco proba 0.3723148707582766==================================================================
==================================================================

ESL-PSC prediction label 0, eco proba 0.3393416313974775
==================================================================
(103, 51316) (1, 51316)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51153) (1, 51153)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.3113928791131838
==================================================================
ESL-PSC prediction label 1, eco proba 0.6457887620796217
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.42011280851883853
==================================================================
ESL-PSC prediction label 0, eco proba 0.437958429586712
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.2839900543429784
==================================================================
ESL-PSC prediction label 1, eco proba 0.7125401233367258
==================================================================
(103, 51267) (1, 51267)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 1, eco proba 0.5739497911994934
==================================================================
ESL-PSC prediction label 0, eco proba 0.237094930359853
==================================================================
ESL-PSC prediction label 1, eco proba 0.6732507800964075
==================================================================
(103, 51147) (1, 51147)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51170) (1, 51170)
ESL-PSC prediction label 1, eco proba 0.6152382375797214
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.4198937999811087
==================================================================
(103, 49296) (1, 49296)
(103, 51133) (1, 51133)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 49144) (1, 49144)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51169) (1, 51169)
ESL-PSC prediction label 0, eco proba 0.3330485617806792
==================================================================
ESL-PSC prediction label 0, eco proba 0.25393852982842596
==================================================================
ESL-PSC prediction label 0, eco proba 0.25292702742366524
==================================================================
ESL-PSC prediction label 0, eco proba 0.2747751300079653
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.4094879693852672
==================================================================
(103, 51146) (1, 51146)
ESL-PSC prediction label 1, eco proba 0.7057837052565137
==================================================================
(103, 51197) (1, 51197)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 49252) (1, 49252)
(103, 51189) (1, 51189)
ESL-PSC prediction label 1, eco proba 0.691261744242201
==================================================================
ESL-PSC prediction label 0, eco proba 0.30768204843716374
==================================================================
eval (0.0, '东非狒狒')
ESL prediction label [0], eco proba [[0.74785147 0.25214853]]
(103, 49262)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(1, 49262)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51165) (1, 51165)
ESL-PSC prediction label 1, eco proba 0.7060636788930077ESL-PSC prediction label 0, eco proba 0.37242841196994725
==================================================================

==================================================================
ESL-PSC prediction label 0, eco proba 0.2678202973142575
==================================================================
ESL-PSC prediction label 0, eco proba 0.28736124434261073
==================================================================
(103, 51163) (1, 51163)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 1, eco proba 0.5458477384586403
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51310) (1, 51310)
(103, 52959) (1, 52959)
(103, 49467) (1, 49467)
(103, 51126) (1, 51126)
(103, 51169) (1, 51169)
(103, 51163) (1, 51163)
ESL-PSC prediction label 0, eco proba 0.2841782567773095
==================================================================
ESL-PSC prediction label 1, eco proba 0.6940850100913697
==================================================================
(103, 51273) (1, 51273)
ESL-PSC prediction label 0, eco proba 0.298539335527135
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 49143) (1, 49143)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.4265641511566903
==================================================================
ESL-PSC prediction label 0, eco proba 0.29834021846539205
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51168) (1, 51168)
(103, 51150) (1, 51150)
(103, 51298) (1, 51298)
ESL-PSC prediction label 0, eco proba 0.2826864290579602
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.31672910680312255
==================================================================
(103, 48797) (1, 48797)
(103, 51385) (1, 51385)
ESL-PSC prediction label 0, eco proba 0.26698159710139624
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.31556094538234897
==================================================================
ESL-PSC prediction label 0, eco proba 0.38315899504601675
==================================================================

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.35403151867481875
==================================================================
ESL-PSC prediction label 0, eco proba 0.28446471823740477
==================================================================
eval (1.0, '江豚')
ESL prediction label [1], eco proba [[0.32478223 0.67521777]]

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)
/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 1, eco proba 0.7002989428823684
==================================================================
ESL-PSC prediction label 0, eco proba 0.2877133326325684
==================================================================
ESL-PSC prediction label 0, eco proba 0.27296339044495943
==================================================================
(103, 51227) (1, 51227)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51171) (1, 51171)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 49270) (1, 49270)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

ESL-PSC prediction label 0, eco proba 0.31722422679944623
==================================================================
(103, 51192) (1, 51192)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 48937) (1, 48937)
(103, 49207) (1, 49207)
(103, 51149) (1, 51149)
(103, 51158) (1, 51158)
ESL-PSC prediction label 0, eco proba 0.4070412772988484
==================================================================
(103, 51167) (1, 51167)
(103, 51077) (1, 51077)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51126) (1, 51126)
(103, 51104) (1, 51104)
ESL-PSC prediction label 0, eco proba 0.33090458713266324
==================================================================
ESL-PSC prediction label 0, eco proba 0.24760052204489785
==================================================================
(103, 51203) (1, 51203)
(103, 51133) (1, 51133)
(103, 51138) (1, 51138)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

(103, 51147) (1, 51147)

/tmp/ipykernel_1576809/659598544.py:25: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  summary_top100 = summary_df.groupby('gene', group_keys=False).apply(get_top_n, n=100)

eval (0.0, '绿猴')
ESL prediction label [0], eco proba [[0.74497454 0.25502546]]
(103, 51225) (1, 51225)
eval (1.0, '太平洋短吻海豚')
ESL prediction label [1], eco proba [[0.3123932 0.6876068]]
(103, 49192) (1, 49192)
eval (0.0, '倭黑猩猩')
ESL prediction label [0], eco proba [[0.72683375 0.27316625]]
(103, 51136) (1, 51136)
eval (0.0, '小家鼠')
ESL prediction label [0], eco proba [[0.70279696 0.29720304]]
eval (0.0, '智人')
ESL prediction label [0], eco proba [[0.74413432 0.25586568]]
eval (1.0, '帕拉斯獒蝠')
ESL prediction label [1], eco proba [[0.33088058 0.66911942]]
eval (0.0, '藏酋猴')
ESL prediction label [0], eco proba [[0.72835023 0.27164977]]
eval (1.0, '大卫鼠耳蝠')
ESL prediction label [1], eco proba [[0.35980832 0.64019168]]
eval (0.0, '恒河猴')
ESL prediction label [0], eco proba [[0.74843928 0.25156072]]
eval (0.0, '玻利维亚松鼠猴')
ESL prediction label [0], eco proba [[0.73986227 0.26013773]]
eval (0.0, '黑叶猴')
ESL prediction label [0], eco proba [[0.74036746 0.25963254]]
eval (1.0, '大棕蝠')
ESL prediction label [1], eco proba [[0.33046788 0.66953212]]
eval (0.0, '水牛')
ESL prediction label [0], eco proba [[0.72457918 0.27542082]]
eval (0.0, '野双峰驼')
ESL prediction label [0], eco proba [[0.70763103 0.29236897]]
eval (1.0, '小棕蝠')
ESL prediction label [1], eco proba [[0.37510939 0.62489061]]
eval (0.0, '八齿鼠')
ESL prediction label [0], eco proba [[0.65920664 0.34079336]]
eval (0.0, '银白长臂猿')
ESL prediction label [0], eco proba [[0.7292449 0.2707551]]
eval (0.0, '白顶白眉猴')
ESL prediction label [0], eco proba [[0.74847261 0.25152739]]
eval (0.0, '狮尾狒狒')
ESL prediction label [0], eco proba [[0.74752422 0.25247578]]
eval (0.0, '金刺毛鼠')
ESL prediction label [0], eco proba [[0.70793565 0.29206435]]
eval (1.0, '埃及果蝠')
ESL prediction label [1], eco proba [[0.42945939 0.57054061]]
eval (0.0, '苏门答腊猩猩')
ESL prediction label [0], eco proba [[0.73886351 0.26113649]]
eval (0.0, '白颊长臂猿')
ESL prediction label [0], eco proba [[0.73680619 0.26319381]]
eval (0.0, '马来大狐蝠')
ESL prediction label [1], eco proba [[0.43933964 0.56066036]]
eval (1.0, '小马岛猬')
ESL prediction label [0], eco proba [[0.63806118 0.36193882]]
eval (0.0, '灰海豹')
ESL prediction label [0], eco proba [[0.7064538 0.2935462]]
eval (1.0, '普通鼩鼱')
ESL prediction label [0], eco proba [[0.54898664 0.45101336]]
eval (0.0, '小须鲸')
ESL prediction label [0], eco proba [[0.50243699 0.49756301]]
eval (1.0, '布氏鼠耳蝠')
ESL prediction label [1], eco proba [[0.37646731 0.62353269]]
eval (0.0, '狐獴')
ESL prediction label [0], eco proba [[0.67532649 0.32467351]]
eval (0.0, '西部低地大猩猩')
ESL prediction label [0], eco proba [[0.72095488 0.27904512]]
eval (0.0, '开普金鼹')
ESL prediction label [0], eco proba [[0.65279994 0.34720006]]
eval (1.0, '大鼠耳蝠')
ESL prediction label [1], eco proba [[0.31926037 0.68073963]]
eval (1.0, '鼩鼹')
ESL prediction label [0], eco proba [[0.64310828 0.35689172]]
eval (0.0, '夏威夷僧海豹')
ESL prediction label [0], eco proba [[0.71146025 0.28853975]]
eval (0.0, '食蟹猕猴')
ESL prediction label [0], eco proba [[0.74033963 0.25966037]]
eval (0.0, '羚牛')
ESL prediction label [0], eco proba [[0.73524338 0.26475662]]
eval (0.0, '棕卷尾猴')
ESL prediction label [0], eco proba [[0.74719346 0.25280654]]
eval (0.0, '加拿大马鹿')
ESL prediction label [0], eco proba [[0.69947244 0.30052756]]
eval (0.0, '豚尾猕猴')
ESL prediction label [0], eco proba [[0.73458553 0.26541447]]
eval (1.0, '库氏伏翼')
ESL prediction label [1], eco proba [[0.33090618 0.66909382]]
eval (0.0, '猎豹')
ESL prediction label [0], eco proba [[0.7224535 0.2775465]]
eval (0.0, '山魈')
ESL prediction label [0], eco proba [[0.72089023 0.27910977]]
eval (1.0, '洪都拉斯肩章果蝠')
ESL prediction label [1], eco proba [[0.31780368 0.68219632]]
eval (0.0, '安哥拉疣猴')
ESL prediction label [0], eco proba [[0.74602437 0.25397563]]
eval (1.0, '抹香鲸')
ESL prediction label [0], eco proba [[0.51036501 0.48963499]]
eval (0.0, '瘤牛')
ESL prediction label [0], eco proba [[0.70852149 0.29147851]]
eval (0.0, '非洲象')
ESL prediction label [0], eco proba [[0.68508434 0.31491566]]
ESL-PSC prediction label 1, eco proba 0.561395174383065
==================================================================
eval (0.0, '川金丝猴')
ESL prediction label [0], eco proba [[0.73172834 0.26827166]]
ESL-PSC prediction label 0, eco proba 0.3866661354163481
==================================================================
ESL-PSC prediction label 0, eco proba 0.4512815701917934
==================================================================
ESL-PSC prediction label 0, eco proba 0.40055040587735025
==================================================================
ESL-PSC prediction label 1, eco proba 0.6350501430033946
==================================================================
ESL-PSC prediction label 1, eco proba 0.6004863622599935
==================================================================
ESL-PSC prediction label 0, eco proba 0.25390206042552244
==================================================================
ESL-PSC prediction label 0, eco proba 0.2532672161429771
==================================================================
ESL-PSC prediction label 1, eco proba 0.5597176044751916
==================================================================
ESL-PSC prediction label 0, eco proba 0.22643123168249388
==================================================================
ESL-PSC prediction label 1, eco proba 0.7059281397250029
==================================================================
ESL-PSC prediction label 1, eco proba 0.5915634130638213
==================================================================
ESL-PSC prediction label 0, eco proba 0.31716112154114645
==================================================================
ESL-PSC prediction label 0, eco proba 0.4257877223772551
==================================================================
ESL-PSC prediction label 0, eco proba 0.2538657280316817
==================================================================
ESL-PSC prediction label 1, eco proba 0.5593831110629677

==================================================================ESL-PSC prediction label 0, eco proba 0.24938285124118872
==================================================================
ESL-PSC prediction label 1, eco proba 0.6933246774612002
==================================================================
ESL-PSC prediction label 1, eco proba 0.580912775149829
==================================================================
ESL-PSC prediction label 0, eco proba 0.2525717221580911
==================================================================
ESL-PSC prediction label 0, eco proba 0.2536418082809434
==================================================================
ESL-PSC prediction label 0, eco proba 0.2986087482515951
==================================================================
ESL-PSC prediction label 0, eco proba 0.2538403017638236
==================================================================
ESL-PSC prediction label 0, eco proba 0.3250495368370466
==================================================================
ESL-PSC prediction label 0, eco proba 0.2537908988739709
==================================================================
ESL-PSC prediction label 0, eco proba 0.254226498257966
==================================================================
ESL-PSC prediction label 0, eco proba 0.2924524981901337
==================================================================
ESL-PSC prediction label 0, eco proba 0.3151103297013598
==================================================================
ESL-PSC prediction label 0, eco proba 0.26164279421860615
==================================================================
ESL-PSC prediction label 0, eco proba 0.2541151661759362
==================================================================
ESL-PSC prediction label 0, eco proba 0.31819747333594633
==================================================================
ESL-PSC prediction label 0, eco proba 0.24271294412813463
==================================================================
ESL-PSC prediction label 0, eco proba 0.36832147648764924
==================================================================
ESL-PSC prediction label 0, eco proba 0.35133708591286034
==================================================================
ESL-PSC prediction label 0, eco proba 0.25452425435273607
==================================================================
ESL-PSC prediction label 1, eco proba 0.6576721791474491
==================================================================
ESL-PSC prediction label 0, eco proba 0.37098361945797387
==================================================================
ESL-PSC prediction label 0, eco proba 0.25761234086894896
==================================================================
ESL-PSC prediction label 0, eco proba 0.27146781071753817
==================================================================
ESL-PSC prediction label 0, eco proba 0.27558120642303535
==================================================================
ESL-PSC prediction label 0, eco proba 0.27639324797336084
==================================================================
ESL-PSC prediction label 0, eco proba 0.4932762126399998
==================================================================
ESL-PSC prediction label 1, eco proba 0.6302188427634869
==================================================================
ESL-PSC prediction label 0, eco proba 0.25332415863187996
==================================================================
ESL-PSC prediction label 1, eco proba 0.5859043722900027
==================================================================
ESL-PSC prediction label 0, eco proba 0.36152272892876264
==================================================================
ESL-PSC prediction label 0, eco proba 0.2542037415771575
==================================================================
ESL-PSC prediction label 0, eco proba 0.2538297640844089
==================================================================
ESL-PSC prediction label 0, eco proba 0.3325273899553326
==================================================================
ESL-PSC prediction label 0, eco proba 0.3131550565331156
==================================================================
ESL-PSC prediction label 0, eco proba 0.27928676637312166
==================================================================
ESL-PSC prediction label 0, eco proba 0.28244464594254176
==================================================================
Processing complete. Total records collected: 728

In [11]:
new_res = []
for i in range(104):
    tmp = all_results[7*i:7*i + 7]
    idx = tmp[0]
    label = tmp[1]
    idx_cn = tmp[2]
    pred_1 = tmp[3][0]
    pred_prob_1 = tmp[4][0][1]
    pred_2 = tmp[5]
    pred_prob_2 = tmp[6]
    new_res.append([idx, label, idx_cn, pred_1, pred_prob_1, pred_2, pred_prob_2])
df = pd.DataFrame(new_res)
df.columns = ['species','label','species_cn','esl_label','esl_eco_prob','esl_psc_label','esl_psc_eco_prob']
df.index = df['species'].values 
df.to_csv('esl_pred_v2.csv')

In [10]:
df

,species,label,species_cn,esl_label,esl_eco_prob,esl_psc_label,esl_psc_eco_prob
Bos_mutus,Bos_mutus,0.0,野牦牛,0,0.279495,0,0.266982
Ochotona_princeps,Ochotona_princeps,0.0,美洲鼠兔,0,0.317306,0,0.419894
Pan_troglodytes,Pan_troglodytes,0.0,黑猩猩,0,0.258839,0,0.253939

In [12]:
idx_1 = df['esl_label'].values != df['label'].values 
print(idx_1.sum())

idx_2= df['esl_psc_label'].values != df['label'].values 
print(idx_2.sum())

print(df['species_cn'][idx_1])
print(df['species_cn'][idx_2])

8
5
Pteropus_giganteus     印度狐蝠
Pteropus_alecto         黑狐蝠
ZWS                     猪尾鼠
Echinops_telfairi      小马岛猬
Pteropus_vampyrus     马来大狐蝠
Sorex_araneus          普通鼩鼱
shrew_mole               鼩鼹
Physeter_catodon        抹香鲸
Name: species_cn, dtype: object
Panthera_tigris_altaica     东北虎
Echinops_telfairi          小马岛猬
Rousettus_aegyptiacus      埃及果蝠
Sorex_araneus              普通鼩鼱
shrew_mole                   鼩鼹
Name: species_cn, dtype: object

In [13]:
df.loc[idx_1]

,species,label,species_cn,esl_label,esl_eco_prob,esl_psc_label,esl_psc_eco_prob
Pteropus_giganteus,Pteropus_giganteus,0.0,印度狐蝠,1,0.622166,0,0.315561
Pteropus_alecto,Pteropus_alecto,0.0,黑狐蝠,1,0.591863,0,0.282686
ZWS,ZWS,1.0,猪尾鼠,0,0.393366,1,0.561395
Echinops_telfairi,Echinops_telfairi,1.0,小马岛猬,0,0.361939,0,0.451282
Pteropus_vampyrus,Pteropus_vampyrus,0.0,马来大狐蝠,1,0.560660,0,0.257612
Sorex_araneus,Sorex_araneus,1.0,普通鼩鼱,0,0.451013,0,0.386666
shrew_mole,shrew_mole,1.0,鼩鼹,0,0.356892,0,0.400550
Physeter_catodon,Physeter_catodon,1.0,抹香鲸,0,0.489635,1,0.585904

### 准备全部数据

In [68]:
leave_species_id = meta_df.index

In [69]:
for _, species_id in enumerate(leave_species_id):
    print(f'{_} {species_id} =====================================')
    # species_id = 'ZWS'

    '''创建save_dir'''
    save_dir = f'103_leave/{species_id}'
    os.makedirs(save_dir,exist_ok=True)

    ### 加速计算，使用预计算好的104 物种的summary, 只保留前50000 NMI feature 参与计算
    summary_df_pre = pd.read_csv('/home/rsun@ZHANGroup.local/hqy_new/paper_result/summary_df.csv', index_col=0)
    summary_df_pre = summary_df_pre.sort_values(by='score', ascending=False)
    pre_feature = summary_df_pre.index[:20000]

    feature_df = pd.read_parquet('/home/rsun@ZHANGroup.local/hqy_new/data_717/feature_df/data_raw.parquet').T
    feature_df = feature_df.loc[:,pre_feature]
    meta_df = pd.read_csv('/home/rsun@ZHANGroup.local/hqy_new/metadata/metadata_1.csv',index_col= 0)

    train_id = meta_df['label'].values != 2
    train_species = meta_df.index[train_id]

    feature_df = feature_df.loc[train_species,:]
    meta_df = meta_df.loc[train_species, :]

    train_species = list(train_species)
    train_species.remove(species_id)

    test_feature = feature_df.loc[species_id,:].values

    feature_df = feature_df.loc[train_species,:]
    meta_df = meta_df.loc[train_species,:]
    print(f"""train species num {feature_df.shape[0]} \n 
    ======== pos number {(meta_df['label'].values == 1).sum()} \n
    ======== neg number {(meta_df['label'].values == 0 ).sum()}""")

    '''perform feature selection'''

    score_map_4 = {4: 1, 3:0.95, 2: 0.9, 1:0.1, 0:0}
    score_map_5 = {5: 1, 4: 0.9, 3: 0.75, 2: 0.5, 1:0.1,0: 0}

    ### 计算nmi
    feature_num = feature_df.shape[1]
    assert (meta_df.index == feature_df.index).all()

    y = meta_df['label'].values
    nmi_list = []


    for i in tqdm(range(feature_num)):
        y_pred = feature_df.iloc[:,i].values 
        nmi = NMI(y, y_pred)
        nmi_list.append(nmi)

    ### 获取eco mutation
    eco_idx = meta_df['label'].values == 1 
    eco_feature = feature_df.loc[eco_idx,:]
    eco_mutation = eco_feature.mode(axis = 0).iloc[0,:].values  

    ### 获取eco mutation cover 数目  4支或5支
    cover_res = {}
    eco_meta = meta_df.loc[eco_idx, :]

    clade_num = 5
    for key in ['啮齿目','真盲缺目','非洲兽目','翼手目','鲸目']:
        
        if key not in eco_meta['order_chinese_new'].values:
            cover_res[key] = np.zeros(len(eco_mutation))
            clade_num = 4 ## 至多只有1个回声谱系消失
        else:
            idx = eco_meta['order_chinese_new'] == key 
            cover_res[key] = (eco_feature.loc[idx,:] == eco_mutation).sum(axis = 0) / idx.sum()
    cover_df = pd.DataFrame(cover_res)
    cover_df.loc[:,'NMI'] = nmi_list 
    cover_df.loc[:,'Eco_Mode'] = eco_mutation 
    cover_df.loc[:,'eco_cover'] = (cover_df.loc[:,['啮齿目','真盲缺目','非洲兽目','翼手目','鲸目']] > 0).sum(1)
    if clade_num == 4:
        cover_df.loc[:,'cover_score'] = cover_df.loc[:,'eco_cover'].map(score_map_4)
    if clade_num == 5: 
        cover_df.loc[:,'cover_score'] = cover_df.loc[:,'eco_cover'].map(score_map_5)

    cover_df.loc[:,'score'] = cover_df.loc[:,'cover_score'] * cover_df.loc[:,'NMI']
    cover_df = cover_df.sort_values(by='score', ascending=False)

    '''save data'''
    cover_df = cover_df.iloc[:10000,:]
    feature_df = pd.read_parquet('/home/rsun@ZHANGroup.local/hqy_new/data_717/feature_df/data_raw.parquet').T
    feature_df = feature_df.loc[:,cover_df.index]
        
    meta_df = pd.read_csv('/home/rsun@ZHANGroup.local/hqy_new/metadata/metadata_1.csv',index_col= 0)
    train_id = meta_df['label'].values != 2
    train_species = meta_df.index[train_id]

    feature_df = feature_df.loc[train_species,:]
    meta_df = meta_df.loc[train_species, :]

    cover_df.to_csv(os.path.join(save_dir, 'df_summary.csv'))
    feature_df.to_csv(os.path.join(save_dir, 'df_feature.csv'))
    meta_df.to_csv(os.path.join(save_dir, 'df_meta.csv'))

0 Chrysochloris_asiatica =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 797.82it/s]

1 Balaenoptera_acutorostrata_scammoni =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:24<00:00, 800.02it/s]

2 Balaenoptera_musculus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 789.60it/s]

3 Echinops_telfairi =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 783.59it/s]

4 Delphinapterus_leucas =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 797.13it/s]

5 Globicephala_melas =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 798.17it/s]

6 Lagenorhynchus_obliquidens =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 788.15it/s]

7 Lipotes_vexillifer =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 796.07it/s]

8 Monodon_monoceros =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 791.47it/s]

9 Neophocaena_asiaeorientalis_asiaeorientalis =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 792.72it/s]

10 Orcinus_orca =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 794.60it/s]

11 Phocoena_sinus =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 795.50it/s]

12 Physeter_catodon =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:24<00:00, 804.55it/s]

13 Tursiops_truncatus =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 793.68it/s]

14 Acinonyx_jubatus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 789.85it/s]

15 Acomys_russatus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 789.22it/s]

16 Arvicanthis_niloticus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 784.47it/s]

17 Bison_bison_bison =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 788.85it/s]

18 Bos_indicus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 793.94it/s]

19 Bos_mutus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 787.29it/s]

20 Bos_taurus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 797.10it/s]

21 Bubalus_bubalis =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 798.64it/s]

22 Budorcas_taxicolor =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 789.12it/s]

23 Callithrix_jacchus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 787.63it/s]

24 Camelus_bactrianus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:26<00:00, 767.17it/s]

25 Camelus_dromedarius =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 795.74it/s]

26 Camelus_ferus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 791.82it/s]

27 Capra_hircus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 783.73it/s]

28 Cebus_imitator =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 793.69it/s]

29 Ceratotherium_simum_simum =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 795.87it/s]

30 Cercocebus_atys =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 794.79it/s]

31 Cervus_canadensis =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 794.25it/s]

32 Chlorocebus_sabaeus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 794.59it/s]

33 Colobus_angolensis_palliatus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 787.14it/s]

34 Condylura_cristata =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 789.01it/s]

35 Elephas_maximus_indicus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 785.30it/s]

36 Enhydra_lutris_kenyoni =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:24<00:00, 803.29it/s]

37 Equus_asinus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 788.39it/s]

38 Equus_przewalskii =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:24<00:00, 800.29it/s]

39 Equus_quagga =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 795.12it/s]

40 Gorilla_gorilla_gorilla =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:24<00:00, 800.65it/s]

41 Halichoerus_grypus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 786.68it/s]

42 Homo_sapiens =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 779.10it/s]

43 Hylobates_moloch =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 791.33it/s]

44 Ictidomys_tridecemlineatus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:26<00:00, 768.23it/s]

45 Leopardus_geoffroyi =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 792.58it/s]

46 Loxodonta_africana =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 793.43it/s]

47 Macaca_fascicularis =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 798.69it/s]

48 Macaca_mulatta =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 784.12it/s]

49 Macaca_nemestrina =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 793.54it/s]

50 Macaca_thibetana_thibetana =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 799.95it/s]

51 Mandrillus_leucophaeus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 794.04it/s]

52 Marmota_flaviventris =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 792.20it/s]

53 Marmota_marmota_marmota =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 788.28it/s]

54 Marmota_monax =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 788.84it/s]

55 Nannospalax_galili =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 797.10it/s]

56 Neomonachus_schauinslandi =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 792.78it/s]

57 Nomascus_leucogenys =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 770.26it/s]

58 Ochotona_curzoniae =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 798.95it/s]

59 Ochotona_princeps =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 796.78it/s]

60 Octodon_degus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 789.37it/s]

61 Ovis_aries =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:24<00:00, 800.48it/s]

62 Pan_paniscus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 789.19it/s]

63 Pan_troglodytes =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 798.41it/s]

64 Panthera_tigris_altaica =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 789.88it/s]

65 Papio_anubis =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 789.59it/s]

66 Piliocolobus_tephrosceles =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 792.55it/s]

67 Pongo_abelii =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 793.50it/s]

68 Propithecus_coquereli =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 796.91it/s]

69 Rhinopithecus_bieti =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:24<00:00, 804.24it/s]

70 Rhinopithecus_roxellana =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 796.53it/s]

71 Saimiri_boliviensis_boliviensis =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 786.99it/s]

72 Sapajus_apella =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 788.28it/s]

73 Suricata_suricatta =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 792.88it/s]

74 Theropithecus_gelada =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 785.45it/s]

75 Trachypithecus_francoisi =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 792.91it/s]

76 Tupaia_chinensis =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 794.22it/s]

77 Urocitellus_parryii =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 786.54it/s]

78 Ursus_americanus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 788.10it/s]

79 Ursus_maritimus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 794.50it/s]

80 Vicugna_pacos =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 793.69it/s]

81 Artibeus_jamaicensis =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 792.54it/s]

82 Desmodus_rotundus =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 792.31it/s]

83 Eptesicus_fuscus =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 791.16it/s]

84 Hipposideros_armiger =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:24<00:00, 804.27it/s]

85 Miniopterus_natalensis =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 794.77it/s]

86 Molossus_molossus =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 789.93it/s]

87 Myotis_brandtii =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 788.17it/s]

88 Myotis_davidii =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 798.60it/s]

89 Myotis_lucifugus =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 787.21it/s]

90 Myotis_myotis =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:26<00:00, 768.03it/s]

91 Phyllostomus_discolor =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 781.28it/s]

92 Phyllostomus_hastatus =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 793.07it/s]

93 Pipistrellus_kuhlii =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 795.88it/s]

94 Rhinolophus_ferrumequinum =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 780.48it/s]

95 Sorex_araneus =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 797.26it/s]

96 Sturnira_hondurensis =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 787.48it/s]

97 Pteropus_alecto =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 795.53it/s]

98 Pteropus_giganteus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 788.74it/s]

99 Pteropus_vampyrus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 786.92it/s]

100 Rousettus_aegyptiacus =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 788.58it/s]

101 Mus_musculus =====================================
train species num 103

    ======== pos number 30

    ======== neg number 73

100%|██████████| 20000/20000 [00:25<00:00, 799.03it/s]

102 shrew_mole =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 793.26it/s]

103 ZWS =====================================
train species num 103

    ======== pos number 29

    ======== neg number 74

100%|██████████| 20000/20000 [00:25<00:00, 791.95it/s]

In [20]:
summary_df_pre = pd.read_csv('/home/rsun@ZHANGroup.local/hqy_new/paper_result/summary_df.csv', index_col=0)
summary_df_pre = summary_df_pre.sort_values(by='score', ascending=False)

In [ ]:
cover_res = {}
eco_meta = meta_df.loc[eco_idx, :]

clade_num = 5
for key in ['啮齿目','真盲缺目','非洲兽目','翼手目','鲸目']:
    
    if key not in eco_meta['order_chinese_new'].values:
        cover_res[key] = np.zeros(len(eco_mutation))
        clade_num = 4
    else:
        idx = eco_meta['order_chinese_new'] == key 
        cover_res[key] = (eco_feature.loc[idx,:] == eco_mutation).sum(axis = 0) / idx.sum()
cover_df = pd.DataFrame(cover_res)
cover_df.loc[:,'NMI'] = nmi_list 
cover_df.loc[:,'Eco_Mode'] = eco_mutation 
cover_df.loc[:,'eco_cover'] = (cover_df.loc[:,['啮齿目','真盲缺目','非洲兽目','翼手目','鲸目']] > 0).sum(1)

In [53]:
summary_df_pre

,NMI,Eco_Mode,gene,非洲兽目,鲸目,啮齿目,真盲缺目,翼手目,eco_cover,eco_cover_score,score
MRO_68,6.940434e-01,M,MRO,0.0,0.8,1.0,1.0,1.0000,4,0.90,6.246390e-01
SLC26A5_496,5.719839e-01,M,SLC26A5,1.0,1.0,1.0,0.5,0.8750,5,1.00,5.719839e-01
ZC3H3_249,6.251362e-01,P,ZC3H3,1.0,0.9,0.0,0.5,0.8750,4,0.90,5.626226e-01
CWF19L1_403,6.808954e-01,I,CWF19L1,0.0,1.0,0.0,0.5,0.8750,3,0.75,5.106715e-01
CCDC92_3,5.628020e-01,A,CCDC92,1.0,0.9,1.0,0.0,0.6250,4,0.90,5.065218e-01
...,...,...,...,...,...,...,...,...,...,...,...
PKD1_10,2.285072e-06,L,PKD1,0.0,0.7,1.0,0.0,0.6875,3,0.75,1.713804e-06
DGCR2_111,5.281625e-07,G,DGCR2,1.0,0.6,0.0,0.5,0.5625,4,0.90,4.753462e-07
DGCR2_110,5.281625e-07,L,DGCR2,1.0,0.6,0.0,0.5,0.5625,4,0.90,4.753462e-07
DGCR2_109,5.281625e-07,F,DGCR2,1.0,0.6,0.0,0.5,0.5625,4,0.90,4.753462e-07
ANKRD11_1012,5.281625e-07,D,ANKRD11,1.0,0.0,0.0,0.0,1.0000,2,0.50,2.640812e-07

In [ ]:
### 获取eco mutation
eco_idx = meta_df['label'].values == 1 
eco_feature = feature_df.loc[eco_idx,:]
eco_mutation = eco_feature.mode(axis = 0).iloc[0,:].values

In [30]:
eco_mutation

,MRO_68,SLC26A5_496,ZC3H3_249,CWF19L1_403,CCDC92_3,SLC26A5_307,GLB1_334,ANXA1_211,FOXK1_411,NT5C1A_26,...,ZNF638_533,HDAC6_841,POLRMT_1174,NACAD_467,COBLL1_442,ZNF646_1478,F5_1329,PDCD11_1481,TLR2_160,PDZD2_1746
0,M,M,P,I,A,S,V,K,S,H,...,-,K,T,-,A,L,-,R,S,Q
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,P,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN